package com.campus.activity.model.query;

public enum QueryIntent {
    ACTIVITY_LIST,
    ACTIVITY_REGISTRATION_LIST,
    WAITLIST_TOP,
    MY_REGISTRATION_LIST,
    CHECK_IN_STATUS,
    ABSENCE_LIST,
    LOW_RATING_FEEDBACK,
    MY_FEEDBACK_LIST,
    CREDIT_RISK,
    CREDIT_RECORDS,
    NOTIFICATION_LIST,
    CAMPUS_WITHOUT_ACTIVITY,
    ORGANIZER_PARTICIPANT_STUDENTS
}
